game.Players.LocalPlayer.Character.Suit.UpperTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.UpperTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.UpperTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.UpperTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.UpperTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.UpperTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.UpperTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.UpperTorso.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.LeftUpperArm.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftUpperArm.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftUpperArm.Part:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftUpperArm.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftUpperArm.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.RightUpperArm.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightUpperArm.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightUpperArm.Part:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightUpperArm.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightUpperArm.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.RightLowerArm.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightLowerArm.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.LeftLowerArm.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftLowerArm.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.LeftHand.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftHand.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftHand.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.RightHand.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightHand.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightHand.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.LowerTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LowerTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LowerTorso.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LowerTorso.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.RightUpperLeg.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightUpperLeg.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightUpperLeg.Part:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.LeftUpperLeg.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftUpperLeg.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftUpperLeg.Part:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.RightLowerLeg.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightLowerLeg.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.RightLowerLeg.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.LeftLowerLeg.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftLowerLeg.Union:Destroy()
                game.Players.LocalPlayer.Character.Suit.LeftLowerLeg.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.RightFoot.Union:Destroy()
            end
                game.Players.LocalPlayer.Character.Suit.LeftFoot.Union:Destroy()
            end
